# Generated by Django 5.1.2 on 2024-11-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gt', 'Гость'), ('cl', 'Клиент'), ('sc', 'Сервисная компания'), ('mn', 'Менеджер')], default='cl', max_length=2, verbose_name='Роль'),
        ),
    ]
