# Generated by Django 5.1.2 on 2024-10-29 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('eq', 'Модель техники'), ('en', 'Модель двигателя'), ('tr', 'Модель трансмиссии'), ('da', 'Модель ведущего моста'), ('sa', 'Модель управляемого моста'), ('mt', 'Вид ТО'), ('fn', 'Узел отказа'), ('rm', 'Способ восстановления')], max_length=2, verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_serial', models.CharField(max_length=100, unique=True, verbose_name='Зав.№ машины')),
                ('engine_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав.№ двигателя')),
                ('transmission_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав.№ трансмиссии')),
                ('drive_axle_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав.№ ведущего моста')),
                ('steer_axle_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав.№ управляемого моста')),
                ('supply_contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=100, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Адрес поставки (эксплуатации)')),
                ('model_options', models.TextField(blank=True, null=True, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'cl'}, on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_user', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('service_company', models.ForeignKey(limit_choices_to={'role': 'sc'}, on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('drive_axle_model', models.ForeignKey(limit_choices_to={'category': 'da'}, on_delete=django.db.models.deletion.RESTRICT, related_name='drive_axle_model', to='api.reference', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(limit_choices_to={'category': 'en'}, on_delete=django.db.models.deletion.RESTRICT, related_name='engine_model', to='api.reference', verbose_name='Модель двигателя')),
                ('equipment_model', models.ForeignKey(limit_choices_to={'category': 'eq'}, on_delete=django.db.models.deletion.RESTRICT, related_name='equipment_model', to='api.reference', verbose_name='Модель техники')),
                ('steer_axle_model', models.ForeignKey(limit_choices_to={'category': 'sa'}, on_delete=django.db.models.deletion.RESTRICT, related_name='steer_axle_model', to='api.reference', verbose_name='Модель управляемого моста')),
                ('transmission_model', models.ForeignKey(limit_choices_to={'category': 'tr'}, on_delete=django.db.models.deletion.RESTRICT, related_name='transmission_model', to='api.reference', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('engine_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказ-наряда')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_equipment', to='api.equipment', verbose_name='Машина')),
                ('service_company', models.ForeignKey(blank=True, limit_choices_to={'role': 'sc'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('maintenance_type', models.ForeignKey(limit_choices_to={'category': 'mt'}, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_type', to='api.reference', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('engine_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('spare_parts', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('repair_date', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(editable=False, verbose_name='Время простоя техники')),
                ('service_company', models.ForeignKey(limit_choices_to={'role': 'sc'}, on_delete=django.db.models.deletion.RESTRICT, related_name='claim_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_equipment', to='api.equipment', verbose_name='Машина')),
                ('failure_node', models.ForeignKey(limit_choices_to={'category': 'fn'}, on_delete=django.db.models.deletion.RESTRICT, related_name='failure_node', to='api.reference', verbose_name='Узел отказа')),
                ('repair_method', models.ForeignKey(limit_choices_to={'category': 'rm'}, on_delete=django.db.models.deletion.RESTRICT, related_name='repair_method', to='api.reference', verbose_name='Способ восстановления')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
