# Generated by Django 5.1.2 on 2024-10-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='supply_contract',
            new_name='contract',
        ),
    ]
