# Generated by Django 5.1.2 on 2024-10-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_supply_contract_equipment_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='failure_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_equipment', to='api.equipment', verbose_name='Зав. № машины'),
        ),
    ]
