# Generated by Django 5.1.2 on 2024-11-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_claim_failure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_equipment', to='api.equipment', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_equipment', to='api.equipment', verbose_name='Модель техники'),
        ),
    ]
