# Generated by Django 5.1.2 on 2024-11-04 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_claim_equipment_alter_maintenance_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_equipment', to='api.equipment', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='failure_node',
            field=models.ForeignKey(limit_choices_to={'category': 'fn'}, on_delete=django.db.models.deletion.CASCADE, related_name='failure_node', to='api.reference', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='repair_method',
            field=models.ForeignKey(limit_choices_to={'category': 'rm'}, on_delete=django.db.models.deletion.CASCADE, related_name='repair_method', to='api.reference', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'role': 'sc'}, on_delete=django.db.models.deletion.CASCADE, related_name='claim_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_equipment', to='api.equipment', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(limit_choices_to={'category': 'mt'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type', to='api.reference', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sc'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
