# Generated by Django 5.1.2 on 2024-11-15 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_claim_equipment_alter_claim_failure_node_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sc'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_company', to=settings.AUTH_USER_MODEL, verbose_name='ТО компания'),
        ),
    ]
