# Generated by Django 5.1.2 on 2024-11-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_maintenance_maintenance_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='failure_description',
            new_name='failure_node_description',
        ),
    ]
