# Generated by Django 5.1.2 on 2024-11-16 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_failure_description_claim_failure_node_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mtc'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_company', to=settings.AUTH_USER_MODEL, verbose_name='Орг-ция ТО'),
        ),
    ]
