# Generated by Django 5.1.2 on 2024-11-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_maintenance_maintenance_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Орг-ция ТО'),
        ),
    ]
