# Generated by Django 5.1.2 on 2024-11-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_maintenance_company_maintenance_maintenance_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
    ]
